data_base:
  username: "userName" # Имя пользователя PostgreSQL
  password: "password" # Пароль пользователя PostgreSQL
  host: "localhost" # хост PostgreSQL
  port: 5432 # Порт PostgreSQL (5432 по умолчанию)
  dbname: "dataBase" # Название базы данных

connector:
  http_port: 8080 # Порт для локального HTTP сервера
  jira_url: "https://issues.apache.org/jira" # url на Jira репозиторий
  issues_per_request: 50 # Количество Issues за 1 запрос
  number_of_goroutines: 8 # Количество потоков при выгрузке из Jira
  max_retry_wait: 30 # Максимальное время ожидания для повторной отправки запроса
  initial_retry_wait: 10 # Начальное время ожидания для повторной отправки запроса
